### ISSUE TITLE
Tester où on peux brancher les relais/boutons

### ISSUE THREAD

**Issue by mosseb** [mosseb/EnemDoubleShutterModule#3]
Vérifier selon les pins que les relais ne s'allume pas au démarrage/reset.
cf "safe pins" 
https://www.esp8266.com/viewtopic.php?f=5&t=11282
https://github.com/nodemcu/nodemcu-firmware/issues/421
A priori, les boutons on s'en fou puisqu'on ne les lit qu'après le reset.

**Comment by Nefus63b** [comment]
Sur l'ESP8266, les GPIO's suivants sont instables au démarrage :
0, 2, 15, 16
Ce qui correspond sur le nodemcu à :
D0, D3, D4, D8

**Comment by mosseb** [comment]
"Safe pins" = pas de passage à 0 lors du boot = gpio4, gpio5, gpio12, gpio13, gpio14 = D1, D2, D5, D6, D7.
D9 (=RX) aussi si on se passe du port série.
Pins sur lesquelles on peux lire tranquiles : D0..D7, D8 (en logique inversée), SD3(=GPIO10)
